### PR TITLE
feat: move neovim flake into the overlay itself

### PR DESCRIPTION
**Pull request by teto**
Maintaing the flake in the official neovim repository became too much of a burden so we are moving it out to a nix-community repository.

This is the opportunity to do more and add automation so that the neovim nix overlay doesnt ever break !

This became a pressing issue so even though this is not perfect yet, let's merge and iterate. 

Note that maintainers are welcome to help with this repo, I would rather focus on nixpkgs.

Kudos to @ribru17 @willruggiano for their help. 

cc my neovim mates @gaetanlepage @mrcjkb and @Kranzes the maintainer

### CODE REVIEW

**Comment by teto** [comment]
haaaa I completely ignored the original flake, not noticing the flake-parts + hercules-ci additions. I am not familiar with flake-parts @Kranzes would you be able to refactor ?

**Comment by willruggiano** [comment]
@teto https://github.com/nix-community/neovim-nightly-overlay/compare/teto/move-neovim-flake...willruggiano:neovim-nightly-overlay:teto/move-neovim-flake

**Comment by Kranzes** [comment]
> @teto [teto/move-neovim-flake...willruggiano:neovim-nightly-overlay:teto/move-neovim-flake](https://github.com/nix-community/neovim-nightly-overlay/compare/teto/move-neovim-flake...willruggiano:neovim-nightly-overlay:teto/move-neovim-flake)

This looks pretty good, just have to make sure the naming of the overlay and outputs stay the same (haven't checked). One improvement could be to split the flake over multiple files (via flake-parts' `imports`) @teto Do you mind rebasing your branch on @willruggiano's? Also test it out.

**Comment by willruggiano** [comment]
I think the previous overlay used "neovim-nightly" so might've messed up the names.

It doesn't make a whole of sense to have neovim-developer in the overlay IMO. The only reasonable usecase for that package is via `--override-input neovim-src /path/to/your/local/neovim`.

And really it will only be useful via an .envrc in your _neovim_ source directory, e.g.
```bash
use flake github:nix-community/neovim-nightly-overlay --override-input neovim-src .
```

so, in a way, it doesn't make sense to even vend a package.neovim-developer at all and _just_ have the devshell

**Comment by teto** [comment]
@willruggiano do you want to become a maintainer of this repo ? looks like you have all the required nix and neovim skills ;)

@gaetanlepage proposed to fix this PR with your code (too bad you didn't patch this PR instead :( ) as he is kinda familar with flake-parts

Neovim-developer can be helpful to dogfood master and find more bugs with ASAN for instance. It's not because you are a few commits behind it's not useful and hopefully we can get the flake regularly updated (daily ? not sure what's the current frequency).

**Comment by willruggiano** [comment]
If you'd like @teto I will happily help maintain here.

As for the neovim-develop package, yeah I get the value of sanitizers. My comment was more so regarding the assumption that the neovim source code is co-located with the flake (which is not the case anymore). Which... I fixed with the neovim-developer shellHook: `export VIMRUNTIME=${neovim-src}/runtime`.

**Comment by teto** [comment]
superseeded by https://github.com/nix-community/neovim-nightly-overlay/pull/516

**Pull request closed without merging**
