### PR TITLE
ci: build on push to master or PR

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by mjlbach** [comment]
@zimbatm The reason I changed this to using a timer is this doesn't trigger when a commit is pushed to GH by the GHA user  https://github.com/nix-community/neovim-nightly-overlay/blob/755373d3935ef578d5e824f9cdddfb2db17c9242/.github/workflows/update-flake.yml#L35-L37

See: https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs

One option is to set up an an auto-merge action on build success for the PR, another is to run the GHA auto-commit action as a robot account with a personal access token under the nix-community organization.

**Comment by zimbatm** [comment]
Please ignore mean, I am using this repo to test out the cachix signing issue :sweat_smile:

**Comment by mjlbach** [comment]
Oh my mistake! I wanted to type all that out anyways because the info is spread out across 3 IRC channels haha. Good luck :)

**Comment by zimbatm** [comment]
@mjlbach ok, I am done with testing and fixed the nix-community cache. While doing that I also cleaned the action a little bit. So this has become a real PR :)

**Comment by mjlbach** [comment]
Thank you! Closes #87

**Comment by mjlbach** [comment]
@zimbatm Do you have opinions on the auto-commit vs. auto-pr method after build, eg whether we should fix the timer issue by switching to making PRs and implementing an auto-merge PR action (thus avoiding needing a robot account) vs making a robot account with a PAT for nix-community org to use the current setup?

**Comment by zimbatm** [comment]
Both solutions seem like workarounds to a deeper problem with how GitHub Actions are designed. As long as you can guarantee that the CI would have passed, by running the same checks, I think that the current design is OK. The only downside is that you have to maintain the guarantee over time, and lose the green checkmarks in the commit history.

Aside from PAT, I think that GitHub Apps also have the capacity to trigger actions. There might be a more generic solution lurking there to generalize the auto-updater pattern. To be investivated.

**Pull request merged**
